<?php

/**
 * @file
 * Install, update and uninstall functions for the basic BAT module.
 */

/**
 * Implements hook_install()
 */
function bat_install() {
  $readme_path = drupal_get_path('module', 'bat') . '/README.md';
  drupal_set_message(t('Thanks for installing BAT! You must also install the BAT php library for this module to function, please see the <a href="@README_LINK">README</a> for more details.', array('@README_LINK' => url($readme_path))));
}
