<?php

/**
 * @file
 * Interface support for the BAT family of modules.
 */

use Roomify\Bat\Event\Event;
use Roomify\Bat\Calendar\Calendar;

/**
 * Implements hook_menu().
 */
function bat_ui_menu() {
  $items = array();

  // Top level "BAT" container.
  $items['admin/bat'] = array(
    'title' => 'BAT',
    'description' => 'Administer BAT.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );

  $items['admin/bat/config'] = array(
    'title' => 'Configuration',
    'description' => 'Configure settings and business rules for BAT management.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('configure bat settings'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;
}

/**
 * Main booking settings form.
 */
function bat_event_settings($form, &$form_state) {
  // Management vertical tabs.
  $form['bat_settings'] = array(
    '#type' => 'vertical_tabs',
    '#weight' => 99,
    '#attached' => array(
      'css' => array(
        array(
          'data' => '#bat-booking-settings .vertical-tabs .form-type-textfield input { width: auto; }',
          'type' => 'inline',
        ),
      ),
    ),
  );

  $form['bat_event_settings'] = array(
    '#type' => 'fieldset',
    '#group' => 'bat_settings',
    '#title' => t('Booking settings'),
  );

  return system_settings_form($form);
}
