<?php

/**
 * @file
 * Manage units - Units are things that can be booked on a nightly basis
 * (e.g. rooms - but also villas bungalows, cars, drills, you-get-the-idea etc).
 */


/**
 * @section Drupal Hooks
 *
 * Drupal Integration.
 */

/**
 * Implements hook_menu().
 */
function bat_unit_menu() {
  $items = array();

  $items['admin/bat/unit-types'] = array(
    'title' => 'Unit Types',
    'description' => 'Add and administer BAT Unit Types.',
    'page callback' => 'bat_unit_type_list',
    // TODO: specific permission?
    'access arguments' => array('administer bat_unit_type_bundle entities'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
    'file path' => drupal_get_path('module', 'bat_unit'),
    'file' => 'bat_unit_types.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_entity_info().
 */
function bat_unit_entity_info() {
  $return['bat_unit'] = array(
    'label' => t('Units'),
    // The entity class and controller class extend the classes provided by the
    // Entity API.
    'entity class' => 'BatUnit',
    'controller class' => 'BatUnitController',
    'base table' => 'bat_units',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'unit_id',
      'bundle' => 'type',
    ),
    // Bundles are defined by the unit bundles below.
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle
    // objects.
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'bat_unit_create',
    'access callback' => 'bat_unit_access',
    'access arguments' => array(
      'user key' => 'uid',
      'access tag' => 'bat_unit_access',
    ),
    'permission labels' => array(
      'singular' => t('unit'),
      'plural' => t('units'),
    ),
    'module' => 'bat_unit',
    // The information below is used by the BatUnitUIController (which extends
    // the EntityDefaultUIController).
    'translation' => array(
      'entity_translation' => array(
        'base path' => 'admin/bat/units/unit/%bat_unit',
        'default settings' => array(
          'default_language' => LANGUAGE_NONE,
          'hide_language_selector' => FALSE,
        ),
      ),
    ),
  );
  // The entity that holds information about the entity types.
  $return['bat_unit_bundle'] = array(
    'label' => t('Unit Bundle'),
    'entity class' => 'BatUnitBundle',
    'controller class' => 'BatUnitBundleController',
    'base table' => 'bat_unit_bundle',
    'fieldable' => TRUE,
    'bundle of' => 'bat_unit',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'bat_unit_bundle_access',
    'module' => 'bat_unit',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/bat/config/unit-bundles',
      'file' => 'bat_unit_bundle.admin.inc',
      'controller class' => 'BatUnitBundleUIController',
    ),
  );

  $return['bat_unit_type'] = array(
    'label' => t('Unit Type'),
    // The entity class and controller class extend the classes provided by the
    // Entity API.
    'entity class' => 'BatUnitType',
    'controller class' => 'BatUnitTypeController',
    'base table' => 'bat_unit_types',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'unit_type_id',
      'bundle' => 'type',
    ),
    // Bundles are defined by the unit bundles below.
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle
    // objects.
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'bat_unit_type_create',
    'access callback' => 'bat_unit_type_access',
    'access arguments' => array(
      'user key' => 'uid',
      'access tag' => 'bat_unit_type_access',
    ),
    'permission labels' => array(
      'singular' => t('unit type'),
      'plural' => t('unit types'),
    ),
    'module' => 'bat_unit',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/bat/config/unit-types',
      'file' => 'bat_unit_type.admin.inc',
      'controller class' => 'BatUnitTypeUIController',
    ),
    // The information below is used by the BatUnitUIController (which extends
    // the EntityDefaultUIController).
    'translation' => array(
      'entity_translation' => array(
        'base path' => 'admin/bat/config/unit-types/unit-type/%bat_unit_type',
        'default settings' => array(
          'default_language' => LANGUAGE_NONE,
          'hide_language_selector' => FALSE,
        ),
      ),
    ),
  );
  // The entity that holds information about the entity types.
  $return['bat_unit_type_bundle'] = array(
    'label' => t('Unit Type Bundle'),
    'entity class' => 'BatUnitTypeBundle',
    'controller class' => 'BatUnitTypeBundleController',
    'base table' => 'bat_unit_type_bundle',
    'fieldable' => TRUE,
    'bundle of' => 'bat_unit_type',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'bat_unit_type_bundle_access',
    'module' => 'bat_unit',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/bat/config/unit-type-bundles',
      'file' => 'bat_unit_type_bundle.admin.inc',
      'controller class' => 'BatUnitTypeBundleUIController',
    ),
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the unit bundles via a hook to avoid a recursion
 * issue as loading the unit bundles requires the entity info as well.
 */
function bat_unit_entity_info_alter(&$entity_info) {
  // Work on Bat Units.
  foreach (bat_unit_get_bundles() as $bundle => $info) {
    $entity_info['bat_unit']['bundles'][$bundle] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/bat/config/unit-bundles/manage/%bat_unit_bundle',
        'real path' => 'admin/bat/config/unit-bundles/manage/' . $bundle,
        'bundle argument' => 5,
        'access arguments' => array('bypass bat_unit entities access'),
      ),
    );
  }
  // Create custom build mode.
  $entity_info['node']['view modes']['bat_list'] = array(
    'label' => t('Bat Results View'),
    'custom settings' => FALSE,
  );

  // Work on Bat Unit Types.
  foreach (bat_unit_get_type_bundles() as $bundle => $info) {
    $entity_info['bat_unit_type']['bundles'][$bundle] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/bat/config/unit-type-bundles/manage/%bat_unit_type_bundle',
        'real path' => 'admin/bat/config/unit-type-bundles/manage/' . $bundle,
        'bundle argument' => 5,
        'access arguments' => array('bypass bat_unit_type entities access'),
      ),
    );
  }
  // Create custom build mode.
  $entity_info['node']['view modes']['bat_list'] = array(
    'label' => t('Bat Results View'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_permission().
 */
function bat_unit_permission() {
  // Permission for Bat Units.
  $permissions = array(
    'administer bat_unit_bundle entities' => array(
      'title' => t('Administer unit bundles'),
      'description' => t('Allows users to add unit bundles and configure their fields.'),
      'restrict access' => TRUE,
    ),
    'view any bat_unit unpublished entity' => array(
      'title' => t('View any unpublished unit'),
      'description' => t('Allows users to view any unpublished unit.'),
      'restrict access' => TRUE,
    ),
    'view own bat_unit unpublished entities' => array(
      'title' => t('View own unpublished units'),
      'description' => t('Allows users to view own unpublished units.'),
    ),
  );

  $permissions += bat_entity_access_permissions('bat_unit');

  // Override view permissions.
  $entity_info = entity_get_info('bat_unit');
  foreach ($entity_info['bundles'] as $bundle_name => $bundle_info) {
    $permissions['view own bat_unit entities of bundle ' . $bundle_name] = array(
      'title' => t('View own published %bundle @entity_bundle', array('@entity_bundle' => 'units', '%bundle' => $bundle_info['label'])),
    );
    $permissions['view any bat_unit entity of bundle ' . $bundle_name] = array(
      'title' => t('View any published %bundle @entity_bundle', array('@entity_bundle' => 'unit', '%bundle' => $bundle_info['label'])),
    );
  }

  // Permission for Bat Unit Types.
  $permissions += array(
    'administer bat_unit_type_bundle entities' => array(
      'title' => t('Administer unit type bundles'),
      'description' => t('Allows users to add unit type bundles and configure their fields.'),
      'restrict access' => TRUE,
    ),
    'view any bat_unit_type unpublished entity' => array(
      'title' => t('View any unpublished unit type'),
      'description' => t('Allows users to view any unpublished unit type.'),
      'restrict access' => TRUE,
    ),
    'view own bat_unit_type unpublished entities' => array(
      'title' => t('View own unpublished unit types'),
      'description' => t('Allows users to view own unpublished unit types.'),
    ),
  );

  $permissions += bat_entity_access_permissions('bat_unit_type');

  // Override view permissions.
  $entity_info = entity_get_info('bat_unit_type');
  foreach ($entity_info['bundles'] as $bundle_name => $bundle_info) {
    $permissions['view own bat_unit_type entities of bundle ' . $bundle_name] = array(
      'title' => t('View own published %bundle @entity_bundle', array('@entity_bundle' => 'unit types', '%bundle' => $bundle_info['label'])),
    );
    $permissions['view any bat_unit_type entity of bundle ' . $bundle_name] = array(
      'title' => t('View any published %bundle @entity_bundle', array('@entity_bundle' => 'unit type', '%bundle' => $bundle_info['label'])),
    );
  }

  return $permissions;
}

/**
 * Implements hook_query_TAG_alter().
 */
function bat_unit_query_bat_unit_access_alter(QueryAlterableInterface $query) {
  // Look for an unit base table to pass to the query altering function or else
  // assume we don't have the tables we need to establish order related altering
  // right now.
  foreach ($query->getTables() as $table) {
    if ($table['table'] === 'bat_units') {
      bat_entity_access_query_alter($query, 'bat_unit', $table['alias']);
      break;
    }
  }

  // Look for an unit type base table to pass to the query altering function or else
  // assume we don't have the tables we need to establish order related altering
  // right now.
  foreach ($query->getTables() as $table) {
    if ($table['table'] === 'bat_unit_types') {
      bat_entity_access_query_alter($query, 'bat_unit_type', $table['alias']);
      break;
    }
  }
}

/**
 * Implements hook_theme().
 */
function bat_unit_theme() {
  return array(
    'bat_unit' => array(
      'render element' => 'elements',
      'template' => 'bat_unit',
    ),
    'bat_unit_extra_data' => array(
      'variables' => array('unit_extra_data', 'unit' => NULL),
      'template' => 'bat_unit-extra-data',
    ),
    'bat_unit_type' => array(
      'render element' => 'elements',
      'template' => 'bat_unit_type',
    ),
    'bat_unit_type_extra_data' => array(
      'variables' => array('unit_type_extra_data', 'unit_type' => NULL),
      'template' => 'bat_unit_type-extra-data',
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function bat_unit_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'bat_unit') . '/views',
  );
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function bat_unit_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Create an action link on the Units admin page for adding new units.
  if ($root_path == 'admin/bat/units') {
    $item = menu_get_item('admin/bat/units/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }

  // Create an action link on the unit types admin page for adding new unit types.
  elseif ($root_path == 'admin/bat/unit-types') {
    $item = menu_get_item('admin/bat/unit-types/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * @section Bat Unit
 *
 * The following code deals with Bat Units and their bundles. (entity types)
 */
/**
 * Determines whether the given user has access to a unit.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param BatUnit $unit
 *   Optionally a unit or a unit bundle to check access for. If nothing is
 *   given, access for all units is determined.
 * @param object $account
 *   The user to check for. Leave it to NULL to check for the global user.
 *
 * @return boolean
 *   Whether access is allowed or not.
 */
function bat_unit_access($op, $unit = NULL, $account = NULL) {
  return bat_entity_access($op, $unit, $account, 'bat_unit');
}

/**
 * Filters units based on permissions for multiple values.
 */
function bat_unit_access_filter($op, $units = array(), $account = NULL) {
  $filtered_units = array();

  // If no user object is supplied, the access check is for the current user.
  if (empty($account)) {
    $account = $GLOBALS['user'];
  }

  foreach ($units as $key => $unit) {
    if (bat_unit_access($op, $unit, $account)) {
      $filtered_units[$key] = $unit;
    }
  }
  return $filtered_units;
}

/**
 * Access callback for the entity API.
 */
function bat_unit_bundle_access($op, $bundle = NULL, $account = NULL) {
  return user_access('administer bat_unit_bundle entities', $account);
}

/**
 * Implements hook_bat_entity_access_OP_condition_ENTITY_TYPE_alter().
 */
function bat_unit_bat_entity_access_view_condition_bat_unit_alter(&$conditions, $context) {
  $account = $context['account'];

  if (user_access('view any bat_unit unpublished entity', $account)) {
    return;
  }

  $old_conditions = $conditions;
  $conditions = db_and();

  if ($account->uid && user_access('view own bat_unit unpublished entities', $account)) {
    $or = db_and()
      ->condition($context['base_table'] . '.status', 0)
      ->condition($context['base_table'] . '.uid', $account->uid);
    $conditions->condition(db_or()
      ->condition($or)
      ->condition($context['base_table'] . '.status', 1)
    );

  }
  else {
    $conditions->condition($context['base_table'] . '.status', 1);
  }

  if ($old_conditions->count()) {
    $conditions->condition($old_conditions);
  }
}

/**
 * Access callback: Checks whether the user has permission to add a unit.
 *
 * @return bool
 *   TRUE if the user has add permission, otherwise FALSE.
 *
 * @see node_menu()
 */
function _bat_unit_add_access() {
  if (user_access('administer bat_unit_bundle entities')) {
    // There are no unit bundles defined that the user has permission to
    // create, but the user does have the permission to administer the content
    // types, so grant them access to the page anyway.
    return TRUE;
  }

  $bundles = bat_unit_get_bundles();
  foreach ($bundles as $bundle) {
    if (bat_unit_access('create', bat_unit_create(array('type' => $bundle->type, 'uid' => 0)))) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Gets an array of all unit bundles, keyed by the bundle name.
 *
 * @param string $bundle_name
 *   If set, the bundle with the given name is returned.
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return BatUnitBundle[]
 *   Depending whether $bundle isset, an array of unit bundles or a single one.
 */
function bat_unit_get_bundles($bundle_name = NULL, $reset = FALSE) {
  // entity_load() will get the Entity controller for our unit entity and call
  // the load function of that object.
  $bundles = entity_load_multiple_by_name('bat_unit_bundle', isset($bundle_name) ? array($bundle_name) : FALSE);
  return isset($bundle_name) ? reset($bundles) : $bundles;
}

/**
 * Helper function to easily get unit bundles in an array for use in forms, etc.
 *
 * @return array
 *  An array of unit bundles keyed by bundle name and labels
*/
function bat_unit_bundles_ids() {
  $unit_bundles = array();
  $bundles = bat_unit_get_bundles();
  foreach ($bundles as $bundle) {
    $unit_bundles[$bundle->type] = $bundle->label;
  }

  return $unit_bundles;
}

/**
 * Menu argument loader; Load a unit bundle by string.
 *
 * @param $bundle
 *   The machine-readable name of a unit bundle to load.
 * @param bool $reset
 *   A boolean indicating whether the internal cache should be reset.
 *
 * @return array|false
 *   A unit bundle array or FALSE if $bundle does not exist.
 */
function bat_unit_bundle_load($bundle, $reset = FALSE) {
  return bat_unit_get_bundles($bundle, $reset);
}

/**
 * Fetches a unit object.
 *
 * @param int $unit_id
 *   Integer specifying the unit id.
 * @param bool $reset
 *   A boolean indicating whether the internal cache should be reset.
 * @return BatUnit|false
 *   A fully-loaded $unit object or FALSE if it cannot be loaded.
 *
 * @see bat_unit_load_multiple()
 */
function bat_unit_load($unit_id, $reset = FALSE) {
  $units = bat_unit_load_multiple(array($unit_id), array(), $reset);
  return reset($units);
}

/**
 * Loads multiple units based on certain conditions.
 *
 * @param array $unit_ids
 *   An array of unit IDs.
 * @param array $conditions
 *   An array of conditions to match against the {bat_units} table.
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return array
 *   An array of unit objects, indexed by unit_id.
 *
 * @see entity_load()
 * @see bat_unit_load()
 */
function bat_unit_load_multiple($unit_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('bat_unit', $unit_ids, $conditions, $reset);
}

/**
 * Deletes a unit.
 *
 * @param BatUnit $unit
 *   The BatUnit object that represents the unit to delete.
 */
function bat_unit_delete(BatUnit $unit) {
  $unit->delete();
}

/**
 * Deletes multiple units.
 *
 * @param array $unit_ids
 *   An array of unit IDs.
 */
function bat_unit_delete_multiple(array $unit_ids) {
  entity_get_controller('bat_unit')->delete($unit_ids);
}

/**
 * Creates a unit object.
 *
 * @param array $values
 *   The properties for the new unit bundle.
 */
function bat_unit_create($values = array()) {
  return entity_get_controller('bat_unit')->create($values);
}

/**
 * Saves a unit to the database.
 *
 * @param BatUnit $unit
 *   The Unit object.
 */
function bat_unit_save(BatUnit $unit) {
  return $unit->save();
}

/**
 * Creates a unit object.
 *
 * @param array $values
 *   The properties for the new unit bundle.
 */
function bat_unit_bundle_create($values = array()) {
  return entity_get_controller('bat_unit_bundle')->create($values);
}

/**
 * Saves a unit bundle to the db.
 *
 * @param BatUnitBundle $bundle
 *   The unit bundle to save.
 */
function bat_unit_bundle_save(BatUnitBundle $bundle) {
  $bundle->save();
}

/**
 * Deletes a unit bundle from the db.
 */
function bat_unit_bundle_delete(BatUnitBundle $bundle) {
  $bundle->delete();
}

/**
 * URI callback for units.
 */
function bat_unit_uri(BatUnit $unit) {
  return array(
    'path' => 'unit/' . $unit->unit_id,
  );
}

/**
 * Menu title callback for showing individual entities.
 */
function bat_unit_page_title(BatUnit $unit) {
  return $unit->name;
}

/**
 * Gets a list of Units keyed by id and name in value.
 */
function bat_unit_ids($bundle = '') {
  $units = array();

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'bat_unit');

  if ($bundle != '') {
    $query->entityCondition('bundle', $bundle);
  }

  $result = $query->execute();

  if (count($result) > 0) {
    $entities = entity_load('bat_unit', array_keys($result['bat_unit']));
    foreach ($entities as $unit) {
      $wrapper = entity_metadata_wrapper('bat_unit', $unit);
      $units[$wrapper->unit_id->value()] = $wrapper->name->value();
    }
  }

  return $units;
}

/**
 * Sets up content to show an individual unit.
 */
function bat_unit_page_view($unit, $view_mode = 'full') {
  $controller = entity_get_controller('bat_unit');
  $content = $controller->view(array($unit->unit_id => $unit), $view_mode);

  drupal_set_title($unit->name);

  return $content;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = bat_unit_bundle_operation_form
 * Prevent a unit bundle with associated units from being deleted.
 */
function bat_unit_form_bat_unit_bundle_operation_form_alter(&$form, &$form_state, $form_id) {
  // Check if units of a unit bundle exist before allowing deletion.
  if ($form_state['op'] == 'delete') {
    $unit_bundle = $form_state['bat_unit_bundle'];

    // Load the units associated with this bundle.
    $query = new EntityFieldQuery();

    $query->entityCondition('entity_type', 'bat_unit')
          ->propertyCondition('type', $unit_bundle->type);
    $units = $query->execute();
    if (isset($units['bat_unit']) && count($units['bat_unit'])) {

      // This bundle has associated units, don't allow deletion.
      form_set_error('confirm', t('This unit bundle has associated units. Please delete all units before attempting to delete this unit bundle.'));

      unset($form['description']);
      unset($form['actions']);
      unset($form['confirm']);
    }
  }
}

/**
 * Helper function to generate a list of available unit states for select lists.
 *
 * @return array
 *   Array of available unit states keyed by id.
 */
function bat_unit_state_options($event_type = NULL) {
  $event_states = array();

  $states = bat_event_get_states($event_type);

  foreach ($states as $event_state) {
    $event_states[$event_state['id']] = t($event_state['label']);
  }

  return $event_states;
}

/**
 * Returns an initialized bat bundle array. This is here to help other modules easily and
 * consistently add BAT unit bundles.
 */
function bat_unit_unit_bundle_new() {
  return array(
    'type' => '',
    'label' => '',
    'weight' => '0',
    'data' => array(
      'hourly_availability' => 0,
    ),
    'bat_opening_time' => '',
 );
}


/**
 * The class used for unit entities
 */
class BatUnit extends Entity {

  public function __construct($values = array()) {
    parent::__construct($values, 'bat_unit');
  }

  /**
   * {@inheritdoc}
   */
  protected function defaultLabel() {
    return $this->name;
  }

  /**
   * {@inheritdoc}
   */
  protected function defaultUri() {
    return array('path' => 'unit/' . $this->unit_id);
  }

  /**
   * @param $event_type
   * @return
   */
  public function getDefaultValue($event_type) {
    $unit_bundle = bat_unit_bundle_load($this->type);

    $field = '';
    if (isset($unit_bundle->data[$event_type])) {
      $field = $unit_bundle->data[$event_type];
    }
    if ($field == '') {
      return FALSE;
    }
    else {
      $field_info = field_info_field($field);
      $values = field_get_items('bat_unit', $this, $field);

      if (!empty($values)) {
        if ($field_info['type'] == 'bat_event_state_reference') {
          return $values[0]['state_id'];
        }
        elseif ($field_info['type'] == 'commerce_price') {
          return $values[0]['amount'];
        }
        elseif ($field_info['type'] == 'text') {
          return $values[0]['value'];
        }
      }
      else {
        return FALSE;
      }
    }
  }

  /**
   * @return
   */
  public function getConstraints() {
    $constraints = module_invoke_all('bat_unit_constraints', $this);

    return $constraints;
  }

}

/**
 * The class used for unit bundle entities
 */
class BatUnitBundle extends Entity {

  /**
   * The Unit bundle.
   *
   * @var string
   */
  public $type;

  /**
   * The unit bundle label.
   *
   * @var string
   */
  public $label;

  public function __construct($values = array()) {
    parent::__construct($values, 'bat_unit_bundle');
  }

}

/**
 * The Controller for BatUnit entities
 */
class BatUnitController extends EntityAPIController {

  public function __construct($entityType) {
    parent::__construct($entityType);
  }

  /**
   * Creates a unit.
   *
   * @param array $values
   *   The properties for the new unit bundle.
   *
   * @return BatUnit
   *   A unit object with all default fields initialized.
   */
  public function create(array $values = array()) {
    $unit_bundle = bat_unit_bundle_load($values['type'], TRUE);
    // Add values that are specific to our Unit.
    $values += array(
      'unit_id' => '',
      'is_new' => TRUE,
      'title' => '',
      'created' => '',
      'changed' => '',
    );

    $unit = parent::create($values);

    return $unit;
  }

  /**
   * Overriding the buildContent function to add entity specific fields.
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);

    return $content;
  }

}

/**
 * The Controller for Unit entities.
 */
class BatUnitBundleController extends EntityAPIControllerExportable {

  public function __construct($entityType) {
    parent::__construct($entityType);
  }

  /**
   * Creates a unit bundle.
   *
   * @param array $values
   *   The properties for the new unit bundle.
   *
   * @return BatUnitBundle
   *   A unit bundle object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Unit.
    $values += array(
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $unit_bundle = parent::create($values);

    return $unit_bundle;
  }

}


/**
 * @section Bat Unit Type
 *
 * The following code deals with Bat Unit Types and their bundles. (entity types)
 *
 * Bat Unit Types are entities that deal with groups of Units. In a hotel use
 * case, a Unit Type bundle might be called 'Room', and individual entities of
 * type Unit Type might be called 'Single', 'Double', 'Triple', and so on.
 */

/**
 * Determines whether the given user has access to a unit type.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param BatUnitType $unit_type
 *   Optionally a unit type or a unit type bundle to check access for. If nothing is
 *   given, access for all unit types is determined.
 * @param object $account
 *   The user to check for. Leave it to NULL to check for the global user.
 *
 * @return boolean
 *   Whether access is allowed or not.
 */
function bat_unit_type_access($op, $unit_type = NULL, $account = NULL) {
  return bat_entity_access($op, $unit_type, $account, 'bat_unit_type');
}

/**
 * Filters unit types based on permissions for multiple values.
 */
function bat_unit_type_access_filter($op, $unit_types = array(), $account = NULL) {
  $filtered_unit_types = array();

  // If no user object is supplied, the access check is for the current user.
  if (empty($account)) {
    $account = $GLOBALS['user'];
  }

  foreach ($unit_types as $key => $unit_type) {
    if (bat_unit_type_access($op, $unit_type, $account)) {
      $filtered_unit_types[$key] = $unit_type;
    }
  }
  return $filtered_unit_types;
}

/**
 * Access callback for the entity API.
 */
function bat_unit_type_bundle_access($op, $bundle = NULL, $account = NULL) {
  return user_access('administer bat_unit_type_bundle entities', $account);
}

/**
 * Implements hook_bat_entity_access_OP_condition_ENTITY_TYPE_alter().
 */
function bat_unit_type_bat_entity_access_view_condition_bat_unit_type_alter(&$conditions, $context) {
  $account = $context['account'];

  if (user_access('view any bat_unit_type unpublished entity', $account)) {
    return;
  }

  $old_conditions = $conditions;
  $conditions = db_and();

  if ($account->uid && user_access('view own bat_unit_type unpublished entities', $account)) {
    $or = db_and()
      ->condition($context['base_table'] . '.status', 0)
      ->condition($context['base_table'] . '.uid', $account->uid);
    $conditions->condition(db_or()
      ->condition($or)
      ->condition($context['base_table'] . '.status', 1)
    );

  }
  else {
    $conditions->condition($context['base_table'] . '.status', 1);
  }

  if ($old_conditions->count()) {
    $conditions->condition($old_conditions);
  }
}

/**
 * Access callback: Checks whether the user has permission to add a unit type.
 *
 * @return bool
 *   TRUE if the user has add permission, otherwise FALSE.
 *
 * @see node_menu()
 */
function _bat_unit_type_add_access() {
  if (user_access('administer bat_unit_type_bundle entities')) {
    // There are no unit type bundles defined that the user has permission to
    // create, but the user does have the permission to administer the content
    // types, so grant them access to the page anyway.
    return TRUE;
  }

  $bundles = bat_unit_get_type_bundles();
  foreach ($bundles as $bundle) {
    if (bat_unit_type_access('create', bat_unit_type_create(array('type' => $bundle->type, 'uid' => 0)))) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Gets an array of all unit type bundles, keyed by the bundle name.
 *
 * @param string $bundle_name
 *   If set, the bundle with the given name is returned.
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return BatUnitTypeBundle[]
 *   Depending whether $bundle isset, an array of unit type bundles or a single one.
 */
function bat_unit_get_type_bundles($bundle_name = NULL, $reset = FALSE) {
  // entity_load() will get the Entity controller for our unit type entity and call
  // the load function of that object.
  $bundles = entity_load_multiple_by_name('bat_unit_type_bundle', isset($bundle_name) ? array($bundle_name) : FALSE);
  return isset($bundle_name) ? reset($bundles) : $bundles;
}

/**
 * Helper function to easily get unit type bundles in an array for use in forms, etc.
 *
 * @return array
 *  An array of unit type bundles keyed by bundle name and labels
*/
function bat_unit_type_bundles_ids() {
  $unit_type_bundles = array();
  $bundles = bat_unit_get_type_bundles();
  foreach ($bundles as $bundle) {
    $unit_type_bundles[$bundle->type] = $bundle->label;
  }

  return $unit_type_bundles;
}

/**
 * Menu argument loader; Load a unit type bundle by string.
 *
 * @param $bundle
 *   The machine-readable name of a unit type bundle to load.
 * @param bool $reset
 *   A boolean indicating whether the internal cache should be reset.
 *
 * @return array|false
 *   A unit type bundle array or FALSE if $bundle does not exist.
 */
function bat_unit_type_bundle_load($bundle, $reset = FALSE) {
  return bat_unit_get_type_bundles($bundle, $reset);
}

/**
 * Fetches a unit type object.
 *
 * @param int $unit_type_id
 *   Integer specifying the unit type id.
 * @param bool $reset
 *   A boolean indicating whether the internal cache should be reset.
 * @return BatUnitType|false
 *   A fully-loaded $unit_type object or FALSE if it cannot be loaded.
 *
 * @see bat_unit_type_load_multiple()
 */
function bat_unit_type_load($unit_type_id, $reset = FALSE) {
  $unit_types = bat_unit_type_load_multiple(array($unit_type_id), array(), $reset);
  return reset($unit_types);
}

/**
 * Loads multiple unit types based on certain conditions.
 *
 * @param array $unit_type_ids
 *   An array of unit type IDs.
 * @param array $conditions
 *   An array of conditions to match against the {bat_unit_types} table.
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return array
 *   An array of unit type objects, indexed by unit type_id.
 *
 * @see entity_load()
 * @see bat_unit_type_load()
 */
function bat_unit_type_load_multiple($unit_type_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('bat_unit_type', $unit_type_ids, $conditions, $reset);
}

/**
 * Deletes a unit type.
 *
 * @param BatUnitType $unit_type
 *   The BatUnitType object that represents the unit type to delete.
 */
function bat_unit_type_delete(BatUnitType $unit_type) {
  $unit_type->delete();
}

/**
 * Deletes multiple unit types.
 *
 * @param array $unit_type_ids
 *   An array of unit type IDs.
 */
function bat_unit_type_delete_multiple(array $unit_type_ids) {
  entity_get_controller('bat_unit_type')->delete($unit_type_ids);
}

/**
 * Creates a unit type object.
 *
 * @param array $values
 *   The properties for the new unit type bundle.
 */
function bat_unit_type_create($values = array()) {
  return entity_get_controller('bat_unit_type')->create($values);
}

/**
 * Saves a unit type to the database.
 *
 * @param BatUnitType $unit_type
 *   The unit type object.
 */
function bat_unit_type_save(BatUnitType $unit_type) {
  return $unit_type->save();
}

/**
 * Creates a unit type object.
 *
 * @param array $values
 *   The properties for the new unit type bundle.
 */
function bat_unit_type_bundle_create($values = array()) {
  return entity_get_controller('bat_unit_type_bundle')->create($values);
}

/**
 * Saves a unit type bundle to the db.
 *
 * @param BatUnitTypeBundle $bundle
 *   The unit type bundle to save.
 */
function bat_unit_type_bundle_save(BatUnitTypeBundle $bundle) {
  $bundle->save();
}

/**
 * Deletes a unit type bundle from the db.
 */
function bat_unit_type_bundle_delete(BatUnitTypeBundle $bundle) {
  $bundle->delete();
}

/**
 * URI callback for unit types.
 */
function bat_unit_type_uri(BatUnitType $unit_type) {
  return array(
    'path' => 'unit-type/' . $unit_type->unit_type_id,
  );
}

/**
 * Menu title callback for showing individual entities.
 */
function bat_unit_type_page_title(BatUnitType $unit_type) {
  return $unit_type->name;
}

/**
 * Gets a list of unit types keyed by id and name in value.
 */
function bat_unit_type_ids($bundle = '') {
  $unit_types = array();

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'bat_unit_type');

  if ($bundle != '') {
    $query->entityCondition('bundle', $bundle);
  }

  $result = $query->execute();

  if (count($result) > 0) {
    $entities = entity_load('bat_unit_type', array_keys($result['bat_unit_type']));
    foreach ($entities as $unit_type) {
      $wrapper = entity_metadata_wrapper('bat_unit_type', $unit_type);
      $unit_types[$wrapper->unit_type_id->value()] = $wrapper->name->value();
    }
  }

  return $unit_types;
}

/**
 * Gets a list of unit type bundles keyed by id and name in value.
 */
function bat_unit_type_bundle_ids() {
  $unit_type_bundles = array();

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'bat_unit_type_bundle');

  $result = $query->execute();

  if (count($result) > 0) {
    $entities = entity_load('bat_unit_type_bundle', array_keys($result['bat_unit_type_bundle']));
    foreach ($entities as $unit_type_bundle) {
      $wrapper = entity_metadata_wrapper('bat_unit_type_bundle', $unit_type_bundle);
      $unit_type_bundles[$wrapper->id->value()] = $wrapper->label->value();
    }
  }

  return $unit_type_bundles;
}

/**
 * Sets up content to show an individual unit type.
 */
function bat_unit_type_page_view($unit_type, $view_mode = 'full') {
  $controller = entity_get_controller('bat_unit_type');
  $content = $controller->view(array($unit_type->unit_type_id => $unit_type), $view_mode);

  drupal_set_title($unit_type->name);

  return $content;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * FORM_ID = bat_unit_type_bundle_operation_form
 * Prevent a unit type bundle with associated unit types from being deleted.
 */
function bat_unit_form_bat_unit_type_bundle_operation_form_alter(&$form, &$form_state, $form_id) {
  // Check if unit types of a unit type bundle exist before allowing deletion.
  if ($form_state['op'] == 'delete') {
    $unit_type_bundle = $form_state['bat_unit_type_bundle'];

    // Load the unit types associated with this bundle.
    $query = new EntityFieldQuery();

    $query->entityCondition('entity_type', 'bat_unit_type')
          ->propertyCondition('type', $unit_type_bundle->type);
    $unit_types = $query->execute();
    if (isset($unit_types['bat_unit_type']) && count($unit_types['bat_unit_type'])) {

      // This bundle has associated unit types, don't allow deletion.
      form_set_error('confirm', t('This unit type bundle has associated unit types. Please delete all unit types before attempting to delete this unit type bundle.'));

      unset($form['description']);
      unset($form['actions']);
      unset($form['confirm']);
    }
  }
}

/**
 * Returns an initialized bat bundle array. This is here to help other modules easily and
 * consistently add BAT unit type bundles.
 */
function bat_unit_type_bundle_new() {
  return array(
    'type' => '',
    'label' => '',
    'weight' => '0',
    'data' => array(
      'hourly_availability' => 0,
    ),
    'bat_opening_time' => '',
 );
}

/**
 * Support for adding price fields to BAT unit types - something modules such as Rooms make use of.
 *
 * @param $field_name
 * @param $entity_type
 * @param $bundle
 * @param $label
 * @param $description
 * @param int $weight
 * @param bool|FALSE $locked
 * @param bool|FALSE $calculation
 * @param array $display
 * @throws \Exception
 * @throws \FieldException
 */
function bat_unit_type_add_price_field($field_name, $entity_type, $bundle, $label, $description, $weight = 0, $locked = FALSE, $calculation = FALSE, $display = array()) {

  $field = field_info_field($field_name);
  $instance = field_info_instance($entity_type, $field_name, $bundle);

  if (empty($field)) {
    $field = array(
      'field_name' => $field_name,
      'type' => 'commerce_price',
      'cardinality' => 1,
      'entity_types' => array($entity_type),
      'translatable' => FALSE,
      'locked' => $locked,
    );
    $field = field_create_field($field);
  }

  if (empty($instance)) {
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => $entity_type,
      'bundle' => $bundle,
      'description' => $description,

      'label' => $label,
      'required' => TRUE,
      'settings' => array(),

      // Because this widget is locked, we need it to use the full price widget
      // since the currency option can't be adjusted at the moment.
      'widget' => array(
        'type' => 'commerce_price_full',
        'weight' => $weight,
        'settings' => array(
          'currency_code' => 'default',
        ),
      ),

      'display' => array(),
    );

    $entity_info = entity_get_info($entity_type);

    // Spoof the default view mode and node teaser so its display type is set.
    $entity_info['view modes'] += array(
      'default' => array(),
      'node_teaser' => array(),
    );

    foreach ($entity_info['view modes'] as $view_mode => $data) {
      $instance['display'][$view_mode] = $display + array(
          'label' => 'hidden',
          'type' => 'commerce_price_formatted_amount',
          'settings' => array(
            'calculation' => $calculation,
          ),
          'weight' => $weight,
        );
    }

    field_create_instance($instance);
  }
}


/**
 * The class used for unit type entities
 */
class BatUnitType extends Entity {

  public function __construct($values = array()) {
    parent::__construct($values, 'bat_unit_type');
  }

  /**
   * {@inheritdoc}
   */
  protected function defaultLabel() {
    return $this->name;
  }

  /**
   * {@inheritdoc}
   */
  protected function defaultUri() {
    return array('path' => 'unit-type/' . $this->unit_type_id);
  }

  /**
   * @param $event_type
   * @return
   */
  public function getDefaultValue($event_type) {
    $unit_type_bundle = bat_unit_type_bundle_load($this->type);

    $field = '';
    if (isset($unit_type_bundle->data[$event_type])) {
      $field = $unit_type_bundle->data[$event_type];
    }
    if ($field == '') {
      return FALSE;
    }
    else {
      $field_info = field_info_field($field);
      $values = field_get_items('bat_unit_type', $this, $field);

      if (!empty($values)) {
        if ($field_info['type'] == 'bat_event_state_reference') {
          return $values[0]['state_id'];
        }
        elseif ($field_info['type'] == 'commerce_price') {
          return $values[0]['amount'];
        }
        elseif ($field_info['type'] == 'text') {
          return $values[0]['value'];
        }
      }
      else {
        return FALSE;
      }
    }
  }

}

/**
 * The class used for unit type bundle entities
 */
class BatUnitTypeBundle extends Entity {

  /**
   * The unit type bundle.
   *
   * @var string
   */
  public $type;

  /**
   * The unit type bundle label.
   *
   * @var string
   */
  public $label;

  public function __construct($values = array()) {
    parent::__construct($values, 'bat_unit_type_bundle');
  }

}

/**
 * The Controller for BatUnitType entities
 */
class BatUnitTypeController extends EntityAPIController {

  public function __construct($entityType) {
    parent::__construct($entityType);
  }

  /**
   * Creates a unit type.
   *
   * @param array $values
   *   The properties for the new unit type bundle.
   *
   * @return BatUnitType
   *   A unit type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    $unit_type_bundle = bat_unit_type_bundle_load($values['type'], TRUE);
    // Add values that are specific to our unit type.
    $values += array(
      'unit_type_id' => '',
      'is_new' => TRUE,
      'name' => '',
      'created' => '',
      'changed' => '',
    );

    $unit_type = parent::create($values);

    return $unit_type;
  }

  /**
   * Overriding the buildContent function to add entity specific fields.
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);

    return $content;
  }

}

/**
 * The Controller for unit type bundle entities.
 */
class BatUnitTypeBundleController extends EntityAPIControllerExportable {

  public function __construct($entityType) {
    parent::__construct($entityType);
  }

  /**
   * Creates a unit type bundle.
   *
   * @param array $values
   *   The properties for the new unit type bundle.
   *
   * @return BatUnitTypeBundle
   *   A unit type bundle object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our unit type.
    $values += array(
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $unit_type_bundle = parent::create($values);

    return $unit_type_bundle;
  }

}
