<?php

/**
 * @file
 * Install for BAT Fullcalendar module
 */


/**
 * Implements hook_requirements().
 */
function bat_fullcalendar_requirements($phase) {
  if ($phase != 'runtime') {
    return array();
  }

  $library = \Drupal::service('library.discovery')->getLibraryByName('bat_fullcalendar', 'fullcalendar');
  $library_exists = file_exists(DRUPAL_ROOT . '/' . $library['js'][0]['data']);

  return [];
}
