<?php

define('BAT_ADD', 'add');
define('BAT_ADD_DAILY', 'add-daily');
define('BAT_SUB', 'sub');
define('BAT_SUB_DAILY', 'sub-daily');
define('BAT_REPLACE', 'replace');
define('BAT_INCREASE', 'increase');
define('BAT_DECREASE', 'decrease');
define('BAT_DYNAMIC_MODIFIER', 'dynamic_modifier');

define('BAT_ACCESS_ALLOW', 'allow');
define('BAT_ACCESS_DENY', 'deny');
define('BAT_ACCESS_IGNORE', NULL);

define('BAT_THIS_PAGE', 'this');
define('BAT_ALL_PAGES', 'all');
define('BAT_NONE', 'none');

define('BAT_AVAILABILITY_FAILURE', 1);
define('BAT_NO_MATCH', 2);
define('BAT_PER_TYPE', 'bat_per_type');
define('BAT_INDIVIDUAL', 'bat_individual');

define('BAT_OPTION_OPTIONAL', 'optional');
define('BAT_OPTION_MANDATORY', 'mandatory');
define('BAT_OPTION_ONREQUEST', 'on_request');